/**
 * Mailing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MailTemplate model module.
 * @module model/MailTemplate
 * @version 1.0
 */
class MailTemplate {
    /**
     * Constructs a new <code>MailTemplate</code>.
     * @alias module:model/MailTemplate
     */
    constructor() { 
        
        MailTemplate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MailTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MailTemplate} obj Optional instance to populate.
     * @return {module:model/MailTemplate} The populated <code>MailTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MailTemplate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
            if (data.hasOwnProperty('title_template')) {
                obj['title_template'] = ApiClient.convertToType(data['title_template'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MailTemplate.prototype['id'] = undefined;

/**
 * @member {String} template
 */
MailTemplate.prototype['template'] = undefined;

/**
 * @member {String} title_template
 */
MailTemplate.prototype['title_template'] = undefined;

/**
 * @member {String} created_at
 */
MailTemplate.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
MailTemplate.prototype['updated_at'] = undefined;






export default MailTemplate;

