/**
 * Mailing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MailTemplate from './MailTemplate';

/**
 * The QueryMailTemplateResponse model module.
 * @module model/QueryMailTemplateResponse
 * @version 1.0
 */
class QueryMailTemplateResponse {
    /**
     * Constructs a new <code>QueryMailTemplateResponse</code>.
     * @alias module:model/QueryMailTemplateResponse
     */
    constructor() { 
        
        QueryMailTemplateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryMailTemplateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryMailTemplateResponse} obj Optional instance to populate.
     * @return {module:model/QueryMailTemplateResponse} The populated <code>QueryMailTemplateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryMailTemplateResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [MailTemplate]);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} status
 */
QueryMailTemplateResponse.prototype['status'] = undefined;

/**
 * @member {Array.<module:model/MailTemplate>} data
 */
QueryMailTemplateResponse.prototype['data'] = undefined;






export default QueryMailTemplateResponse;

