/**
 * Mailing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendMailRequest model module.
 * @module model/SendMailRequest
 * @version 1.0
 */
class SendMailRequest {
    /**
     * Constructs a new <code>SendMailRequest</code>.
     * @alias module:model/SendMailRequest
     */
    constructor() { 
        
        SendMailRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendMailRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendMailRequest} obj Optional instance to populate.
     * @return {module:model/SendMailRequest} The populated <code>SendMailRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendMailRequest();

            if (data.hasOwnProperty('template_id')) {
                obj['template_id'] = ApiClient.convertToType(data['template_id'], 'Number');
            }
            if (data.hasOwnProperty('customer_email')) {
                obj['customer_email'] = ApiClient.convertToType(data['customer_email'], 'String');
            }
            if (data.hasOwnProperty('template_args')) {
                obj['template_args'] = ApiClient.convertToType(data['template_args'], Object);
            }
            if (data.hasOwnProperty('title_args')) {
                obj['title_args'] = ApiClient.convertToType(data['title_args'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} template_id
 */
SendMailRequest.prototype['template_id'] = undefined;

/**
 * @member {String} customer_email
 */
SendMailRequest.prototype['customer_email'] = undefined;

/**
 * @member {Object} template_args
 */
SendMailRequest.prototype['template_args'] = undefined;

/**
 * @member {Object} title_args
 */
SendMailRequest.prototype['title_args'] = undefined;






export default SendMailRequest;

