/**
 * Mailing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MailTemplate from './MailTemplate';

/**
 * The TemplateResponse model module.
 * @module model/TemplateResponse
 * @version 1.0
 */
class TemplateResponse {
    /**
     * Constructs a new <code>TemplateResponse</code>.
     * @alias module:model/TemplateResponse
     */
    constructor() { 
        
        TemplateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TemplateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateResponse} obj Optional instance to populate.
     * @return {module:model/TemplateResponse} The populated <code>TemplateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = MailTemplate.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} status
 */
TemplateResponse.prototype['status'] = undefined;

/**
 * @member {module:model/MailTemplate} data
 */
TemplateResponse.prototype['data'] = undefined;






export default TemplateResponse;

