/**
 * Mailing API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TemplateRequest model module.
 * @module model/TemplateRequest
 * @version 1.0
 */
class TemplateRequest {
    /**
     * Constructs a new <code>TemplateRequest</code>.
     * @alias module:model/TemplateRequest
     */
    constructor() { 
        
        TemplateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TemplateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TemplateRequest} obj Optional instance to populate.
     * @return {module:model/TemplateRequest} The populated <code>TemplateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateRequest();

            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
            if (data.hasOwnProperty('title_template')) {
                obj['title_template'] = ApiClient.convertToType(data['title_template'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} template
 */
TemplateRequest.prototype['template'] = undefined;

/**
 * @member {String} title_template
 */
TemplateRequest.prototype['title_template'] = undefined;






export default TemplateRequest;

